project:
  type: website
  output-dir: docsfile

website:
  title: "Siyu Li"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "CV"
        href: Siyu Li's CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



